name: py.test
on: push
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - name: Set up code climate
      uses: amancevice/code-climate-action@v0
      with:
        cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}
        command: before-build
    - run: pip install boto3 pytest pytest-cov
    - run: py.test
    - name: Send coverage report
      uses: amancevice/code-climate-action@v0
      with:
        cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}
        command: after-build
